/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas4;

import tugas3.*;

/**
 *
 * @author Edwar Arliman Gea
 */
public class GUI_HJM extends javax.swing.JFrame {

    /**
     * Creates new form GUI_HJM
     */
    public GUI_HJM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmerk = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtproduksi = new javax.swing.JTextField();
        Cmb_Tipe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        memo_hasil = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Btn_tampil = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Merk");

        jLabel2.setText("Model");

        jLabel3.setText("Jumlah Stok");

        jLabel4.setText("Tahun Produksi");

        Cmb_Tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skuter (Scooter)", "Sport Bike", "Naked Bike" }));

        memo_hasil.setColumns(20);
        memo_hasil.setRows(5);
        jScrollPane1.setViewportView(memo_hasil);

        jLabel5.setText("Data Sepada Motor");

        Btn_tampil.setText("Tampilkan");
        Btn_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_tampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cmb_Tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmerk, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txtmodel)
                                .addComponent(txtstok)
                                .addComponent(txtproduksi))
                            .addComponent(Btn_tampil)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtproduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Cmb_Tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_tampil)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_tampilActionPerformed
        // TODO add your handling code here:
        Tipe Motor1 = new Tipe();
        Tipe Motor2 = new Tipe();
        Tipe Motor3 = new Tipe();

        switch (Cmb_Tipe.getSelectedIndex()) {
            case 0:
                Motor1.setMerk(txtmerk.getText());
                Motor1.setModel(txtmodel.getText());
                Motor1.setTahunProduksi(Integer.parseInt(txtproduksi.getText()));
                Motor1.setJumlahStok(Integer.parseInt(txtstok.getText()));
                memo_hasil.setText("");
                memo_hasil.append("Data Sepeda Motor" + "\n");
                memo_hasil.append("Merk: " + Motor1.getMerk() + "\n");
                memo_hasil.append("Model: " + Motor1.getModel() + "\n");
                memo_hasil.append("Jumlah Stok: " + Motor1.getJumlahStok() + "\n");
                memo_hasil.append("Tahun Produksi: " + Motor1.getTahunProduksi() + "\n");
                    memo_hasil.append("Tipe: " + Motor1.getTipe1());
                break;
            case 1:
                Motor2.setMerk(txtmerk.getText());
                Motor2.setModel(txtmodel.getText());
                Motor2.setTahunProduksi(Integer.parseInt(txtproduksi.getText()));
                Motor2.setJumlahStok(Integer.parseInt(txtstok.getText()));
                memo_hasil.setText("");
                memo_hasil.append("Data Sepeda Motor" + "\n");
                memo_hasil.append("Merk: " + Motor2.getMerk() + "\n");
                memo_hasil.append("Model: " + Motor2.getModel() + "\n");
                memo_hasil.append("Jumlah Stok: " + Motor2.getJumlahStok() + "\n");
                memo_hasil.append("Tahun Produksi: " + Motor2.getTahunProduksi() + "\n");
                memo_hasil.append("Tipe: " + Motor2.getTipe2());
                break;
            case 2:
                Motor3.setMerk(txtmerk.getText());
                Motor3.setModel(txtmodel.getText());
                Motor3.setTahunProduksi(Integer.parseInt(txtproduksi.getText()));
                Motor3.setJumlahStok(Integer.parseInt(txtstok.getText()));
                memo_hasil.setText("");
                memo_hasil.append("Data Sepeda Motor" + "\n");
                memo_hasil.append("Merk: " + Motor3.getMerk() + "\n");
                memo_hasil.append("Model: " + Motor3.getModel() + "\n");
                memo_hasil.append("Jumlah Stok: " + Motor3.getJumlahStok() + "\n");
                memo_hasil.append("Tahun Produksi: " + Motor3.getTahunProduksi() + "\n");
                memo_hasil.append("Tipe: " + Motor3.getTipe3());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_Btn_tampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_HJM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_HJM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_HJM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_HJM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_HJM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_tampil;
    private javax.swing.JComboBox<String> Cmb_Tipe;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btncetak1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memo_hasil;
    private javax.swing.JTextField txtmerk;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtproduksi;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
